version: '3.7'
services:
  api:
    image: $API_IMAGE
    container_name: $API_CONTAINER_NAME
    command: bash -c 'yarn && yarn start'
    ports:
      - $API_PORT:$API_PORT
    expose:
      - $API_PORT
    working_dir: $API_WORKING_DIR
    volumes:
      - $API_VOLUME
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: $MYSQL_IMAGE
    container_name: $MYSQL_CONTAINER_NAME
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    expose:
      - $MYSQL_PORT
    env_file:
      - .env
networks:
  default:
    name: $NETWORK
